name: Frontend CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
     run:
       working-directory: hams
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
          cache-dependency-path: hams/package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Check installed packages
        run: |
          npm ls react-router-dom
          ls node_modules/react-router-dom

      - name: Run ESLint
        run: npx eslint src --ext .js,.jsx

      - name: Run Unit Tests
        run: npm test -- --watchAll=false

      - name: Generate Test Coverage
        run: npm test -- --coverage --watchAll=false

      - name: Check Code Formatting
        run: npm run format:check

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: Hospital-Frontend
          path: hams
          format: HTML
          out: reports 

      - name: Trivy FileSystem Scan
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: 'fs'
          scan-ref: './hams'
          format: 'table'
          exit-code: 0
          severity: 'CRITICAL,HIGH'

      - name: Upload OWASP Report
        uses: actions/upload-artifact@v4
        with:
          name: owasp-report
          path: reports

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/hospital-frontend:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/hospital-frontend:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/hospital-devops

            git pull origin main

            cd compose

            docker compose pull frontend

            docker compose up -d frontend

            docker image prune -f
